print("hello world")
name = input("what is your name? ")
print("name")
age = input("how old are you? ")
print("age")
location = input("where do you live? ")
print("location")
print("name")("age")("location") 
print(f"Hello {name}, you are {age} years old and live in {location}.")
print ("location")